# NOTE: 
# - Replace all instances of "your.domain.example.com" with your actual server domain
# - Replace all instances of "/path/to/your_install_dir" with your lichen-markdown install path
# - Change the ssl-settings to point to a working certificate
# - need to follow the instructions for setting up http basic auth and setting auth_basic_user_file below
# (https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)

<VirtualHost *:443>
    ServerName your.domain.example.com
        SSLEngine on
        SSLCertificateFile /path/to/certificate/fullchain.pem
        SSLCertificateKeyFile /path/to/your_private_key/privkey.pem

    ServerAdmin webmaster@your.domain.example.com
    DocumentRoot /path/to/your_install_dir
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /path/to/your_install_dir>
        Options +FollowSymLinks
        AllowOverride All
        <IfVersion >= 2.3>
            Require all granted
        </IfVersion>
        <IfVersion < 2.3>
            order allow,deny
            allow from all
        </IfVersion>
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName your.domain.example.com
    Redirect permanent / https://your.domain.example.com/
</VirtualHost>
