map $is_redirected $auth_type {
	default "Restricted";
	true "off";
}

# NOTE: 
# - need to replace all instances of __INSTALL_DIR__ with your lichen markdown install path
# - need to replace "your.domain.example.com" with your actual server domain
# - need to follow the instructions for setting up http basic auth and setting auth_basic_user_file:
# (https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)
# The basic user file can also be made with the installation script - but you still need to set up http basic auth.
server {
	listen 80;

	root   __INSTALL_DIR__;
	include mime.types;
	index index.md;

	server_name your.domain.example.com;

    location / {
        include mime.types;
        default_type text/html;
        try_files /dist${uri}.html /dist${uri} /dist${uri}index.html @md_handler =404;
    }

    location @md_handler {
        root   __INSTALL_DIR__/lichen-markdown/src;
        include mime.types;

        # --- try .md files
        if (-f ${document_root}${uri}.md) {
            set $redirect_url ${uri}.md;
            set $is_redirected true;
            set $new_url /cms/render.php?${redirect_url};
            rewrite ^(.*)$ $new_url last;
        }

        # --- try index files
        if (-f ${document_root}${uri}index.md) {
            set $redirect_url ${uri}index.md;
            set $is_redirected true;
            rewrite ^(.*)$ /cms/render.php?${redirect_url} last;
        }

        try_files $uri $uri/ =404;
    }

    location /admin {
        return 301 /cms/edit.php;
    }

    location /cms/ {
        root   __INSTALL_DIR__/lichen-markdown/src;
        auth_basic "CMS";
        # the file below needs to be created
        # instructions on how to do so can be found here:
        # https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
        auth_basic_user_file __INSTALL_DIR__/lichen-markdown/.htpasswd;

        fastcgi_split_path_info ^(.+\.php)\?*(\/.+)$;
        set $path_info $fastcgi_path_info;

        fastcgi_pass unix:/run/php/php-fpm.sock;
        include fastcgi_params;

        fastcgi_param REDIRECT_URL $redirect_url if_not_empty;
        fastcgi_param SCRIPT_FILENAME ${document_root}${fastcgi_script_name};
        fastcgi_param PATH_INFO $path_info;

        try_files $fastcgi_script_name =404;
    }


    # no password protection for the render endpoint
    location ~ /cms/render\.php {
        root   __INSTALL_DIR__/lichen-markdown/src;
        fastcgi_split_path_info ^(.+\.php)\?*(\/.+)$;
        set $path_info $fastcgi_path_info;

        fastcgi_pass unix:/run/php/php-fpm.sock;
        include fastcgi_params;

        fastcgi_param REDIRECT_URL $redirect_url if_not_empty;
        fastcgi_param SCRIPT_FILENAME ${document_root}${fastcgi_script_name};
        fastcgi_param PATH_INFO $path_info;

        try_files $fastcgi_script_name =404;
    }

    location /theme/ {
        return 404;
    }

    location /update/ {
        return 404;
    }

}
